/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 分析牌组（同步，约 10–17s）
         * @description 按 url（Moxfield 公开牌组）与 decklist（粘贴文本）的优先级取牌表：
         *     两者都填时文本优先，两者都缺报 MISSING_DECK_SOURCE。
         *     可能的错误 code：
         *     - 400：INVALID_JSON / INVALID_MOXFIELD_URL / INVALID_DECKLIST / MISSING_DECK_SOURCE /
         *       DECK_NO_COMMANDER / DECK_EMPTY
         *     - 429：RATE_LIMITED（Moxfield 上游限流）
         *     - 502：UPSTREAM_CHALLENGE / PRIVATE_OR_FORBIDDEN / NOT_FOUND / DECK_SOURCE_FAILED /
         *       DECK_SOURCE_INVALID / ANALYSIS_FAILED
         */
        post: operations["analyzeDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare-swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 比较换掉一张牌前后的构筑指标
         * @description 可能的错误 code：
         *     - 400：INVALID_JSON / INVALID_SWAP / REMOVE_CARD_NOT_FOUND / COMMANDER_SWAP_NOT_SUPPORTED /
         *       CARD_NOT_FOUND / ILLEGAL_ADDED_CARD / COLOR_IDENTITY_MISMATCH / SINGLETON_VIOLATION /
         *       INVALID_DECKLIST
         *     - 502：CARD_DATA_UNAVAILABLE / COMPARISON_FAILED
         */
        post: operations["compareSwap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按名称查单卡资料
         * @description 可能的错误 code（错误映射复用 swap 语义，见「已知偏差」2）：
         *     - 400：CARD_NAME_REQUIRED / CARD_NOT_FOUND / INVALID_DECKLIST
         *     - 502：CARD_DATA_UNAVAILABLE / COMPARISON_FAILED
         */
        get: operations["lookupCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/build-suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 组牌模式的补充卡建议（排除已选/已见）
         * @description 可能的错误 code：
         *     - 400：INVALID_JSON / COMMANDER_REQUIRED / COMMANDER_NOT_LEGAL
         *     - 404：COMMANDER_NOT_FOUND
         *     - 502：CARD_DATA_UNAVAILABLE / BUILD_POOL_EXHAUSTED / BUILD_SUGGEST_FAILED
         */
        post: operations["buildSuggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/build-lands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 按类别推荐地牌
         * @description 可能的错误 code：
         *     - 400：INVALID_JSON / LAND_CATEGORY_REQUIRED
         *     - 502：LANDS_FAILED
         */
        post: operations["buildLands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/build-staples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 按类别推荐常用单卡
         * @description 可能的错误 code：
         *     - 400：INVALID_JSON / STAPLE_CATEGORY_REQUIRED / CARD_NOT_FOUND
         *     - 502：STAPLES_FAILED
         */
        post: operations["buildStaples"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commander-autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 主将名称自动补全
         * @description 可能的错误 code：
         *     - 400：QUERY_REQUIRED / COMMANDER_NOT_LEGAL
         *     - 404：COMMANDER_NOT_FOUND
         *     - 502：CARD_DATA_UNAVAILABLE / BUILD_POOL_EXHAUSTED / BUILD_SUGGEST_FAILED
         */
        get: operations["commanderAutocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/card-autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 卡牌名称自动补全
         * @description 错误 code 同 commander-autocomplete。
         */
        get: operations["cardAutocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/random-commander": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 随机返回一位主将
         * @description 无请求体。可能的错误 code：
         *     - 400：COMMANDER_NOT_LEGAL / COMMANDER_PAIR_INVALID
         *     - 404：COMMANDER_NOT_FOUND
         *     - 502：RANDOM_COMMANDER_UNAVAILABLE / CARD_DATA_UNAVAILABLE / COMMANDERS_FAILED
         */
        post: operations["randomCommander"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolve-commanders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 把主将名称解析为完整资料并合并色组
         * @description 可能的错误 code：
         *     - 400：INVALID_JSON / COMMANDER_REQUIRED / COMMANDER_NOT_LEGAL / COMMANDER_PAIR_INVALID
         *     - 404：COMMANDER_NOT_FOUND
         *     - 502：RANDOM_COMMANDER_UNAVAILABLE / CARD_DATA_UNAVAILABLE / COMMANDERS_FAILED
         */
        post: operations["resolveCommanders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前构建版本与最新发布版本
         * @description current 为构建时注入的发布 tag（本地开发构建为 "dev"）。latest 是服务端
         *     尽力查询 GitHub Releases 的结果（成功缓存 24h，失败缓存 1h）；查询失败
         *     或断网时为 null，前端据此保持安静。latest.notes 可能缺省（重定向兜底源
         *     不提供发布说明）。
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
            };
        };
        AnalyzeRequest: {
            /** @description Moxfield 公开牌组地址 */
            url?: string;
            /** @description 粘贴的牌表文本；与 url 同时提供时优先生效 */
            decklist?: string;
        };
        CompareSwapRequest: {
            decklist: string;
            remove_name: string;
            add_name: string;
        };
        BuildSuggestRequest: {
            commander: string;
            /** @description 草稿里已加入的卡名 */
            chosen?: string[];
            /** @description 最近两次刷新展示过但未选的卡名 */
            seen?: string[];
            /** @description 期望候选数 */
            count?: number;
        };
        BuildLandsRequest: {
            commander?: string;
            category: string;
            color_identity?: components["schemas"]["ManaColor"][];
        };
        BuildStaplesRequest: {
            commander?: string;
            category: string;
            color_identity?: components["schemas"]["ManaColor"][];
        };
        ResolveCommandersRequest: {
            commanders: string[];
        };
        Analysis: {
            status: string;
            deck: components["schemas"]["DeckSummary"];
            /** @description 以数据源名为键（commandersalt / edh_power_level / …） */
            results: {
                [key: string]: components["schemas"]["ProviderResult"];
            };
            deck_cards: components["schemas"]["DisplayCard"][];
            related_cards: components["schemas"]["DisplayCard"][];
            combos: components["schemas"]["Combo"][];
            combo_suggestions: components["schemas"]["ComboSuggestion"][];
            recommendations: components["schemas"]["RecommendationGroup"][];
            recommendation_keywords: string[];
            /** @description 构筑分类失败时为 null */
            construction_report: components["schemas"]["ConstructionReport"] | null;
            /** @description 法术力基础分析失败时为 null */
            manabase: components["schemas"]["ManabaseReport"] | null;
            /** @description 健康度评估失败时为 null */
            health: components["schemas"]["HealthResult"] | null;
            canonical_decklist: string;
            /** @description 牌表内容哈希，可用作幂等/缓存键 */
            deck_revision: string;
            warnings: string[];
        };
        DeckSummary: {
            id: string;
            name: string;
            commanders: string[];
            card_count: number;
        };
        ProviderResult: {
            /** @description 数据源状态（ok / 出错时的描述） */
            status: string;
            /** @description 数据源自定义指标，各源结构不同 */
            metrics: {
                [key: string]: unknown;
            };
            error: components["schemas"]["ProviderError"] | null;
        };
        ProviderError: {
            code: string;
            message: string;
        };
        Card: {
            oracle_id: string;
            name: string;
            printed_name: string;
            mana_cost: string;
            type_line: string;
            oracle_text: string;
            color_identity: components["schemas"]["ManaColor"][];
            keywords: string[];
            legalities: {
                [key: string]: string;
            };
            /** Format: uri */
            image_normal: string;
            /** Format: uri */
            image_small: string;
            layout: string;
            faces: components["schemas"]["CardFace"][];
            cmc: number;
            produced_mana: components["schemas"]["ManaColor"][];
            power: string;
            /** @description 是否在 Commander Game Changers 名单（以 Scryfall 实时字段为准） */
            game_changer: boolean;
            chinese_name: string;
            chinese_type_line: string;
            chinese_oracle_text: string;
        };
        CardFace: {
            name: string;
            printed_name: string;
            mana_cost: string;
            type_line: string;
            oracle_text: string;
            /** Format: uri */
            image_normal: string;
            /** Format: uri */
            image_small: string;
            game_changer: boolean;
            power: string;
        };
        /** @enum {string} */
        ManaColor: "W" | "U" | "B" | "R" | "G" | "C";
        DisplayCard: {
            card: components["schemas"]["Card"];
            quantity: number;
            commander: boolean;
            land: boolean;
            /** @description 命中的构筑指标 id（ramp/wincon/…） */
            roles: string[];
        };
        Combo: {
            name: string;
            components: components["schemas"]["DisplayCard"][];
            result: string;
            steps: string[];
            sources: string[];
            /** Format: uri */
            source_url: string;
        };
        ComboSuggestion: {
            name: string;
            /** @enum {string} */
            category: "win" | "lifeloss" | "mana" | "turns" | "mill" | "other";
            /** @description 成组合后产生的效果描述 */
            result: string;
            owned: components["schemas"]["DisplayCard"][];
            missing: components["schemas"]["DisplayCard"][];
            /** Format: uri */
            source_url: string;
        };
        RecommendationGroup: {
            header: string;
            tag: string;
            cards: components["schemas"]["RecommendedCard"][];
        };
        RecommendedCard: {
            card: components["schemas"]["Card"];
            synergy: number;
            inclusion_rate: number;
            reason: string;
            /** Format: uri */
            source_url: string;
            keywords: string[];
            fills: components["schemas"]["RecommendationFill"][];
        };
        RecommendationFill: {
            id: string;
            label: string;
            gap: number;
            reason: string;
        };
        ConstructionReport: {
            metrics: components["schemas"]["Metric"][];
            /** @description Spellbook 制胜组合数，参与胜负手指标 */
            wincon_combo_count: number;
        };
        Metric: {
            id: string;
            label: string;
            target: number;
            actual: number;
            gap: number;
            status: string;
            coverage: number;
            incomplete: boolean;
            cards: components["schemas"]["ClassifiedCard"][];
        };
        ClassifiedCard: {
            name: string;
            quantity: number;
            reason: string;
            counts: {
                [key: string]: number;
            };
        };
        ManabaseReport: {
            actual_lands: number;
            target_lands: number;
            land_delta: number;
            average_mana_value: number;
            ramp_and_draw_under_three: number;
            fast_mana: number;
            median_mana_value: number;
            average_mana_value_no_lands: number;
            median_mana_value_no_lands: number;
            total_mana_value: number;
            cost_counts: components["schemas"]["CostCount"][];
            color_pips: {
                [key: string]: number;
            };
            land_color_pips: {
                [key: string]: number;
            };
            colorless_pips: number;
            color_findings: components["schemas"]["ColorFinding"][];
        };
        CostCount: {
            mana_value: number;
            label: string;
            count: number;
            permanent_count: number;
        };
        ColorFinding: {
            color: components["schemas"]["ManaColor"];
            actual_sources: number;
            required_sources: number;
            driving_spell: string;
        };
        HealthResult: {
            score: number;
            /** @description 内部分级；前端只展示 score，不展示字母 */
            grade: string;
            reasons: components["schemas"]["HealthReason"][];
        };
        HealthReason: {
            label: string;
            detail: string;
            score_penalty: number;
        };
        SwapComparison: {
            removed: components["schemas"]["SwapCard"];
            added: components["schemas"]["SwapCard"];
            before: components["schemas"]["SwapDeckState"];
            after: components["schemas"]["SwapDeckState"];
            deltas: components["schemas"]["SwapMetricDelta"][];
            cut_reasons: components["schemas"]["SwapCutReason"][];
            legality: components["schemas"]["SwapLegality"];
            updated_decklist: string;
            deck_revision: string;
        };
        SwapCard: {
            name: string;
        };
        SwapDeckState: {
            card_count: number;
            construction_report: components["schemas"]["ConstructionReport"];
        };
        SwapMetricDelta: {
            id: string;
            label: string;
            before: number;
            after: number;
            delta: number;
            target: number;
        };
        SwapCutReason: {
            role: string;
            label: string;
            reasons: string[];
        };
        SwapLegality: {
            valid: boolean;
            card_count_valid: boolean;
            commander_count_valid: boolean;
            color_identity: components["schemas"]["ManaColor"][];
            issues: string[];
        };
        BuildSuggestResponse: {
            commander_name: string;
            color_identity: components["schemas"]["ManaColor"][];
            candidates: components["schemas"]["BuildCandidate"][];
        };
        BuildCandidate: {
            name: string;
            synergy: number;
            inclusion_rate: number;
            fills: string[];
            card: components["schemas"]["Card"];
            /** Format: uri */
            source_url: string;
            game_changer: boolean;
        };
        LandCategoryResult: {
            category_id: string;
            category_label: string;
            lands: components["schemas"]["LandCategoryEntry"][];
        };
        LandCategoryEntry: {
            name: string;
            card: components["schemas"]["Card"];
        };
        StapleCategoryResult: {
            category_id: string;
            category_label: string;
            staples: components["schemas"]["StapleCategoryEntry"][];
        };
        StapleCategoryEntry: {
            name: string;
            card: components["schemas"]["Card"];
            game_changer: boolean;
        };
        ResolvedCommander: {
            name: string;
            card: components["schemas"]["Card"];
            color_identity: components["schemas"]["ManaColor"][];
            is_partner: boolean;
        };
        AutocompleteResponse: {
            suggestions: string[];
        };
        ResolveCommandersResponse: {
            commanders: components["schemas"]["ResolvedCommander"][];
            color_identity: components["schemas"]["ManaColor"][];
        };
        VersionResponse: {
            /** @description 构建时注入的发布 tag，本地开发构建为 "dev" */
            current: string;
            /** @description 最新发布信息；查询失败或断网时为 null */
            latest: null | components["schemas"]["LatestRelease"];
        };
        LatestRelease: {
            /** @description 发布 tag，如 v20260922-1030 */
            version: string;
            /** @description 发布说明（重定向兜底源不提供，可能缺省） */
            notes?: string;
            /** @description GitHub Releases 页面 */
            release_url: string;
            /** @description 安卓 APK 下载直链 */
            apk_url?: string;
            /** @description Windows 桌面客户端下载直链 */
            exe_url?: string;
        };
    };
    responses: {
        /** @description 请求不合法；code 见各端点 description */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 资源不存在（如主将名拼写无匹配） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 上游服务限流 */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 上游数据源不可用或返回异常 */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    analyzeDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description 完整分析结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["BadGateway"];
        };
    };
    compareSwap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareSwapRequest"];
            };
        };
        responses: {
            /** @description 前后状态对比 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapComparison"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    lookupCard: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 卡牌资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        card: components["schemas"]["Card"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    buildSuggest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildSuggestRequest"];
            };
        };
        responses: {
            /** @description 候选卡列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSuggestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    buildLands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildLandsRequest"];
            };
        };
        responses: {
            /** @description 地牌推荐列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandCategoryResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    buildStaples: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildStaplesRequest"];
            };
        };
        responses: {
            /** @description 单卡推荐列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StapleCategoryResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    commanderAutocomplete: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 候选名称列表（最多 12 个） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    cardAutocomplete: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 候选名称列表（最多 12 个） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    randomCommander: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一位主将 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedCommander"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    resolveCommanders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveCommandersRequest"];
            };
        };
        responses: {
            /** @description 解析结果与合并色组 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveCommandersResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
